### ISSUE TITLE
Conversion of regex to normal pythonic code

### ISSUE THREAD

**Issue by Tihsrah** [Tihsrah/NNST-Sentiment-Analyser#1]
regex code example :

# removal of url
    non_url=re.sub(r'''(?i)\b((?:https?://|www\d{0,3}[.]|[a-z0-9.\-]+[.][a-z]{2,4}/)(?:[^\s()<>]+|\(([^\s()<>]+|(\([^\s()<>]+\)))*\))+(?:\(([^\s()<>]+|(\([^\s()<>]+\)))*\)|[^\s`!()\[\]{};:'".,<>?«»“”‘’]))''', " ", test_data[i])
    
converting these codes to normal logic code.

**Comment by Ben-Ostrovsky** [comment]
Hey man! You can import re to your python code and run regular code directly instead of changing this, but I'd be happy to decode this for you (I have a decoder that wrote a while back). Where can I find all of the ones you want changed, if you still want them changed?

**Comment by Tihsrah** [comment]
@Ben-Ostrovsky   I am now working on a little academic assignment, thus I am unable to accept your assistance with the coding. We are first developing a sentiment analyzer for the English language before moving on to the Hinglish language and attempting to increase accuracy where possible.
Since relatively little research has been done on the native Indian languages, we are also considering expanding it further by adding more of them.

More of the codes are in #code folder. (very little work has been done till now though)

But yes, I would really like to see your decoder for reference.

(I would also really like to connect with you if you worked with nlp so that I could learn from you.)

I'm always willing to collaborate with you and would love to learn from your works.

**Comment by Tihsrah** [comment]
Conversion was not needed as it would slow down the text processing so re was used.
